name: CI/CD
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          clean: true
      - name: Stop process
        run: pm2 stop cwstats-web
      - name: Pull changes
        run: git pull
      - name: Install dependencies for production
        run: npm install
      - name: Build the app
        if: success()
        run: npm run build
      - name: Restart the process
        if: success()
        run: pm2 reload cwstats-web
